[package]
edition = "2021"
name = "chn_ip"
version = "0.1.0"

[dependencies]
reqwest = {version = "0.12.9", features = ["rustls-tls"], default-features = false}
tokio = {version = "1.41.1", features = ["full"]}
